"""Application configuration.

All settings are read from environment variables (optionally via a local
``.env`` file). This keeps secrets and deployment-specific values out of the
source tree and makes the tool easy to configure for different environments.
"""

from __future__ import annotations

from functools import lru_cache
from typing import List

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Strongly-typed application settings loaded from the environment."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # ----- General -------------------------------------------------------
    app_name: str = "NParks Internal Opportunities eDM Generator"
    log_level: str = Field(default="INFO", description="Python logging level.")

    # ----- Persistence ---------------------------------------------------
    # Default is a local SQLite file. Any SQLAlchemy URL is accepted.
    database_url: str = Field(default="sqlite:///./edm.db")

    # ----- Careers@Gov source -------------------------------------------
    careers_base_url: str = Field(default="https://www.careers.gov.sg")
    # The agency to filter vacancies by.
    careers_agency: str = Field(default="National Parks Board")
    # Best-effort JSON search endpoint used by the public portal. The portal's
    # markup/endpoints can change over time, so this is configurable.
    careers_search_url: str = Field(
        default="https://sgcareers-api.spf.gov.sg/api/v2/jobs/search"
    )
    request_timeout: float = Field(default=20.0)
    # Maximum number of vacancies to keep / display.
    max_vacancies: int = Field(default=60)
    # When the live source is unreachable, fall back to the bundled sample
    # dataset so the tool remains demonstrable. Disable in production if you
    # would rather surface an error.
    use_sample_fallback: bool = Field(default=True)

    # ----- Optional automatic refresh schedule --------------------------
    # Off by default: refresh is on demand. Set to true to enable a background
    # schedule. Interval is one of: hourly, daily, weekly.
    auto_refresh_enabled: bool = Field(default=False)
    auto_refresh_interval: str = Field(default="daily")

    # ----- AI summaries --------------------------------------------------
    # If an Anthropic API key is provided, concise summaries are generated by
    # Claude. Otherwise a deterministic extractive fallback is used.
    anthropic_api_key: str = Field(default="")
    anthropic_model: str = Field(default="claude-haiku-4-5-20251001")
    summary_min_words: int = Field(default=25)
    summary_max_words: int = Field(default=40)

    # ----- CORS ----------------------------------------------------------
    cors_origins: List[str] = Field(
        default=["http://localhost:5173", "http://127.0.0.1:5173"]
    )

    @field_validator("cors_origins", mode="before")
    @classmethod
    def _split_origins(cls, value):
        """Allow a comma-separated string in the environment."""
        if isinstance(value, str):
            return [v.strip() for v in value.split(",") if v.strip()]
        return value

    @field_validator("auto_refresh_interval")
    @classmethod
    def _validate_interval(cls, value: str) -> str:
        allowed = {"hourly", "daily", "weekly"}
        if value not in allowed:
            raise ValueError(f"auto_refresh_interval must be one of {allowed}")
        return value


@lru_cache
def get_settings() -> Settings:
    """Return a cached Settings instance."""
    return Settings()
